### PR TITLE
Upgrade Node 16 to Node 20

### LINKED ISSUE #299: GH is deprecating Node.js 16 actions. Upgrade to Node 20 needed
When using the `carvel-setup-action`, from October 23rd, GitHub will start producing a message warning about the future deprecation (Spring 2024) of any Node.js 16 actions due to the fact that Node 16 has reached end of life.

GitHub recommends maintainers to start migrating their actions to Node 20.

More information: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

### PR DESCRIPTION
**Pull request by ThomasVitale**
- Upgrade the action to use Node 20 instead of Node 16.
- Migrate from @zeit/ncc to @vercel/ncc package because the former has been out of maintenance for 3 years and a transition to the latter is recommended. Change done here because @zeit/ncc doesn't provide support for Node 20.

Fixes gh-299

### CODE REVIEW

**Comment by jbrunton** [comment]
Thanks for the PR, @ThomasVitale!

I see the build is failing. I have a hunch this is unrelated and I'll check this now.

I also note that for Enterprise users with self-hosted runners, Node 20 support was only added in August (https://github.com/actions/runner/releases/tag/v2.308.0) so I suspect this may be a breaking change for some. I think when we merge this the next build should be called v2. No action required in this PR, but just a reminder to myself (and an FYI to others).

**Comment by jbrunton** [comment]
@ThomasVitale : Could you do me a favor to fix the build? Either merge, cherry-pick or copy and paste the changes from https://github.com/carvel-dev/setup-action/pull/301 onto your branch?

This PR needs that fix to pass, but my PR also needs (some of) the dependency upgrades in your PR to pass. Between them they should do the job.

**Comment by ThomasVitale** [comment]
@jbrunton thanks for the review. Since my branch is in a fork, I couldn't cherry-pick your commit fixing the tests, so I copied the fix. I hope that's ok.

I agree about bumping the major version for the new release since it could be a breaking change.

**Comment by jbrunton** [comment]
@ThomasVitale : thank you, that all looks good. I'll merge this and create a new version.

**Pull request merged**
