### PR TITLE
chore: replaces vmware-tanzu references with carvel-dev

### LINKED ISSUE #262: vmware-tanzu/carvel-setup-action@v1 disappeared
it seems that `vmware-tanzu/carvel-setup-action@v1` was removed somehow and replaced with `carvel-dev/setup-action@v1`

The action doesnt exist anymore and we get an error: Repository not found

We switched to `carvel-dev/setup-action@v1` and it works but the breaking change was not announced and the readme is still pointing to the old action.

### PR DESCRIPTION
**Pull request by wanis-fahmy**
Resolves https://github.com/carvel-dev/setup-action/issues/262

### CODE REVIEW

**Comment by wanis-fahmy** [comment]
@praveenrewar can you maybe have a look when you have time? I think i was able to change all references but i'm not sure why the build fails

**Comment by praveenrewar** [comment]
> I think i was able to change all references but i'm not sure why the build fails

I don't have enough knowledge about this but I think it has to do with the auto generated code in `dist/index.js`, maybe it shouldn't be committed  🤔 
cc @jbrunton

**Comment by wanis-fahmy** [comment]
>  maybe it shouldn't be committed 🤔

yea I was also surprised it was there initially, I can remove it when @jbrunton confirms

**Comment by jbrunton** [comment]
The `dist/index.js` file is what the action actually runs (see the action.yml file for where this is configured). One could possibly have a job on the main branch to automatically update it, but this repo was copied from the GitHub action template and inherited this approach (of keeping it up to date in source control) at the time.

@praveenrewar : How did you update the dist file? I see if I run this locally that there is indeed a different between what is on this branch and what should be there. You should be able to run `npm run all` to format, build and package the code, then commit that (see also [DEVELOPMENT.md](https://github.com/carvel-dev/setup-action/blob/develop/DEVELOPMENT.md) for reference). If the output from _that_ doesn't work, let me know on Slack and maybe we can investigate this together.

**Comment by jbrunton** [comment]
Sorry, misread my notifications and realised @praveenrewar isn't the contributor of the PR. My question above should be directed at @wanisfahmyDE. Please can you take a look at the above comment and try updating the `dist/index.js` file? Thank you!

**Comment by wanis-fahmy** [comment]
@jbrunton `npm run all` did the trick, all green now 🎉

**Pull request merged**
