### PR TITLE
Add github action to check release download

### PR DESCRIPTION
**Pull request by joaopapereira**
This new workflow is intended to help with the release of new versions of all the Carvel tools.
Running this workflow would try to check all the binaries and download them to ensure the release notes are correct

### CODE REVIEW

**Comment by jbrunton** [comment]
@joaopapereira: Sounds a useful check to have. Couple of questions from me:

1. I see you're using the workflow_dispatch event. What will be triggering that? (E.g. will there be automation elsewhere to trigger it on releases?)
2. Who will be monitoring the outcome, and what actions should they take on a failure? (I'm certainly happy to be one of the people monitoring, but I'd like to confirm how to respond if so.)

**Comment by jbrunton** [comment]
One alternative which comes to mind, though it would be slightly more work (as it would be spread across repos), would be to add a workflow to each carvel app repo which, on the release event, would run this action for that app only. Then each Carvel app would have its own pipeline checking its own release notes, and the failures might be more clearly visible in the relevant repos. (But to be clear, I'm perfectly happy with the approach in this PR; I'm just wondering about what would create visibility most effectively for the Carvel maintainers.)

**Comment by joaopapereira** [comment]
@jbrunton We have a checklist we follow for now with the multiple things we need to do when releasing the tools. The idea is that we add this check as part of that checklist. Basically, we will have to manually run the workflow and check the result by hand.

My initial idea was to create this per repository, but it felt more like the responsibility of the action to ensure it can download all the tools (and a lot less work to have this in all repos 😃). But after thinking a little bit more the automated check might be easier to add to our process.

**Comment by jbrunton** [comment]
@joaopapereira: Thanks for the context! I'm happy either way. Would you like me to go ahead and merge this PR so the option is there, or do you want to think on this further?

**Comment by joaopapereira** [comment]
After some soul searching I think we should do it per repository as you suggested.

**Pull request closed without merging**
